INTEGER FUNCTION BLAS_SET_NUM_THREADS(NT)

#ifdef USE_MKL
#ifdef USE_INTEL
  USE MKL_SERVICE
#endif
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT
#ifdef USE_GNU
  INTEGER, EXTERNAL :: MKL_SET_NUM_THREADS_LOCAL
#endif

  BLAS_SET_NUM_THREADS = MKL_SET_NUM_THREADS_LOCAL(NT)
#else
  USE OMP_LIB
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT

  BLAS_SET_NUM_THREADS = OMP_GET_NUM_THREADS()
  CALL OMP_SET_NUM_THREADS(NT)
#endif

END FUNCTION BLAS_SET_NUM_THREADS
