INTEGER FUNCTION BLAS_SET_NUM_THREADS(NT)

#ifdef USE_MKL
  USE MKL_SERVICE
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT
  BLAS_SET_NUM_THREADS = MKL_SET_NUM_THREADS_LOCAL(NT)
#else
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT
  BLAS_SET_NUM_THREADS = 1
#endif

END FUNCTION BLAS_SET_NUM_THREADS
