INTEGER FUNCTION BLAS_PREPARE(NT)

#ifdef USE_MKL
  USE MKL_SERVICE
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT

  IF (NT .LT. 0) THEN
     BLAS_PREPARE = -1
  ELSE
     IF (MKL_GET_DYNAMIC()) THEN
        BLAS_PREPARE = 3
        CALL MKL_SET_DYNAMIC(0)
     ELSE
        BLAS_PREPARE = 1
     END IF
  END IF
#else
  USE OMP_LIB
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT

  IF (NT .LT. 0) THEN
     BLAS_PREPARE = -1
  ELSE
     IF (OMP_GET_DYNAMIC()) THEN
        BLAS_PREPARE = 2
        CALL OMP_SET_DYNAMIC(.FALSE.)
     ELSE
        BLAS_PREPARE = 0
     END IF
     IF (OMP_GET_NESTED()) THEN
        BLAS_PREPARE = BLAS_PREPARE + 1
        IF (NT .LE. 1) CALL OMP_SET_NESTED(.FALSE.)
     ELSE IF (NT .GT. 1) THEN
        CALL OMP_SET_NESTED(.TRUE.)
     END IF
  END IF
#endif

END FUNCTION BLAS_PREPARE
