INTEGER FUNCTION BLAS_PREPARE(NT)

#ifdef USE_LAPACK_PAR
  USE OMP_LIB
  USE, INTRINSIC :: ISO_C_BINDING
#ifdef USE_MKL
#ifdef USE_INTEL
  USE MKL_SERVICE
#endif
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT
#ifdef USE_GNU
  EXTERNAL :: MKL_SET_DYNAMIC
#endif

  IF (NT .LT. 0) THEN
     BLAS_PREPARE = -1
  ELSE IF (NT .EQ. 1) THEN
     CALL MKL_SET_DYNAMIC(0_c_int)
  ELSE IF (NT .GT. 1) THEN
     CALL MKL_SET_DYNAMIC(1_c_int)
  ELSE ! NT = 0, i.e., sequential MKL
     CONTINUE
  END IF
#else
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT

  IF (NT .LT. 0) THEN
     BLAS_PREPARE = -1
  ELSE IF (NT .EQ. 1) THEN
     CALL OMP_SET_DYNAMIC(.FALSE._c_int)
     CALL OMP_SET_NESTED(.FALSE._c_int)
  ELSE IF (NT .GT. 1) THEN
     CALL OMP_SET_DYNAMIC(.TRUE._c_int)
     CALL OMP_SET_NESTED(.TRUE._c_int)
  ELSE ! NT = 0, i.e., sequential MKL
     CONTINUE
  END IF
#endif
  BLAS_PREPARE = INT(OMP_GET_MAX_ACTIVE_LEVELS())
#else
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NT

  IF ((NT .LT. 0) .OR. (NT .GT. 1)) THEN
     BLAS_PREPARE = -1
  ELSE
     BLAS_PREPARE = 0
  END IF
#endif

END FUNCTION BLAS_PREPARE
