SUBROUTINE BLAS_SET_NUM_THREADS(NT)

#ifdef USE_MKL
  USE MKL_SERVICE
#else
#ifndef USE_OPENBLAS
  USE OMP_LIB
#endif
#endif

  IMPLICIT NONE

  INTEGER, INTENT(IN) :: NT

#ifdef USE_OPENBLAS
  EXTERNAL :: OPENBLAS_SET_NUM_THREADS
#endif

#ifdef USE_MKL
  CALL MKL_SET_NUM_THREADS(NT)
#else
#ifdef USE_OPENBLAS
  CALL OPENBLAS_SET_NUM_THREADS(NT)
#else
  CALL OMP_SET_NUM_THREADS(NT)
#endif
#endif

END SUBROUTINE BLAS_SET_NUM_THREADS
