MODULE HZ

  IMPLICIT NONE

#ifdef LOGICAL_KIND
  INTEGER, PARAMETER :: LWP = LOGICAL_KIND
#else
  INTEGER, PARAMETER :: LWP = KIND(.FALSE.)
#endif

#ifdef INTEGER_KIND
  INTEGER, PARAMETER :: IWP = INTEGER_KIND
#else
  INTEGER, PARAMETER :: IWP = KIND(0)
#endif

#ifdef REAL_KIND
  INTEGER, PARAMETER :: RWP = REAL_KIND
#else
#ifdef DOUBLE_PREC
  INTEGER, PARAMETER :: RWP = KIND(0.0D0)
#else
  INTEGER, PARAMETER :: RWP = KIND(0.0E0)
#endif
#endif

  REAL, PARAMETER :: S_ZERO  =  0.0E0
  REAL, PARAMETER :: S_ONE   =  1.0E0
  REAL, PARAMETER :: S_MONE  = -1.0E0

  DOUBLE PRECISION, PARAMETER :: D_ZERO  =  0.0D0
  DOUBLE PRECISION, PARAMETER :: D_ONE   =  1.0D0
  DOUBLE PRECISION, PARAMETER :: D_MONE  = -1.0D0

  INTERFACE MY_FMA
#ifdef HAVE_FMA
     MODULE PROCEDURE MY_SFMA, MY_DFMA
#else
     FUNCTION MY_SFMA(A, B, C) BIND(C,name='fmaf')
       USE, INTRINSIC :: ISO_C_BINDING
       REAL(c_float), VALUE :: A, B, C
       REAL(c_float) :: MY_SFMA
     END FUNCTION MY_SFMA
     FUNCTION MY_DFMA(A, B, C) BIND(C,name='fma')
       USE, INTRINSIC :: ISO_C_BINDING
       REAL(c_double), VALUE :: A, B, C
       REAL(c_double) :: MY_DFMA
     END FUNCTION MY_DFMA
#endif
  END INTERFACE MY_FMA

  INTERFACE MY_RSQRT
#ifdef USE_INTEL
     PURE FUNCTION SRSQRT(X) BIND(C,NAME='invsqrtf')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       REAL(c_float), INTENT(IN), VALUE :: X
       REAL(c_float) :: SRSQRT
     END FUNCTION SRSQRT
     PURE FUNCTION DRSQRT(X) BIND(C,NAME='invsqrt')
       USE, INTRINSIC :: ISO_C_BINDING
       IMPLICIT NONE
       REAL(c_double), INTENT(IN), VALUE :: X
       REAL(c_double) :: DRSQRT
     END FUNCTION DRSQRT
#else
     MODULE PROCEDURE SRSQRT, DRSQRT
#endif
  END INTERFACE MY_RSQRT

CONTAINS

#ifdef HAVE_FMA
  PURE REAL FUNCTION MY_SFMA(A, B, C)
    IMPLICIT NONE
    REAL, INTENT(IN) :: A, B, C
    !DIR$ FMA
    MY_SFMA = A * B + C
  END FUNCTION MY_SFMA

  PURE DOUBLE PRECISION FUNCTION MY_DFMA(A, B, C)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: A, B, C
    !DIR$ FMA
    MY_DFMA = A * B + C
  END FUNCTION MY_DFMA
#endif

#ifndef USE_INTEL
  ELEMENTAL REAL FUNCTION SRSQRT(X)
    IMPLICIT NONE
    REAL, INTENT(IN) :: X
    SRSQRT = S_ONE / SQRT(X)
  END FUNCTION SRSQRT

  ELEMENTAL DOUBLE PRECISION FUNCTION DRSQRT(X)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: X
    DRSQRT = D_ONE / SQRT(X)
  END FUNCTION DRSQRT
#endif

! Threading support.
#include "BLAS_PREPARE.F90"
#include "BLAS_SET_NUM_THREADS.F90"
#include "GET_NTHR.F90"

! I/O support.
#include "GET_IOUNIT.F90"

! Timing support.
#include "TIMER_START.F90"
#include "TIMER_STOP.F90"
#include "TIMER_PRINT.F90"
#include "TIMER2DBLE.F90"

! Shuffler.
#include "INITSH.F90"
#include "BACKSH.F90"

! Partitioner.
#include "PARTBL.F90"

! Stepper.
#include "STRINI.F90"
#include "MMSTEP.F90"

! Hari-Zimmermann, Levels 0, 1, 2.
#include "ZIMMER.F90"

END MODULE HZ
