SUBROUTINE INIT_THRS()

#ifdef USE_MKL
  USE MKL_SERVICE
#endif
  USE OMP_LIB

  IF (.NOT. OMP_GET_NESTED()) CALL OMP_SET_NESTED(.TRUE.)

#ifdef USE_MKL
  IF (MKL_GET_DYNAMIC() .NE. 0) CALL MKL_SET_DYNAMIC(0)
#endif
  IF (OMP_GET_DYNAMIC()) CALL OMP_SET_DYNAMIC(.FALSE.)

END SUBROUTINE INIT_THRS
